version: 2
jobs:
  full_test:
    docker:
      - image: golang
    working_directory: /go/src/gomoku
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS # create the test results directory
      - run:
          name: Run unit tests
          command: go test gomoku/gomoku
      - run:
          name: Build Pepito
          working_directory: "../../bin"
          command: go build gomoku/pepito
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  commit:
    jobs:
      - full_test
